import test from "node:test"; import assert from "node:assert/strict";
import { EventsController } from "@/features/events/controller"; import { renderEventsPage } from "@/pages/EventsPage";
const card=(overrides:any={})=>({code:"cup",day:"2026-09-13",type:"path",name:"Cup",description:"<b>safe</b>",dates:[],available:true,rules:"Rules",player_name:"",min_correct:1,career_path:[],image_url:null,points:2,bonus_available:true,progress:{attempts:0,finished:false,solved:false,points:0},leaderboard:[],...overrides});
const client=(responses:any[])=>({post:async (_:string,_p:any)=>{const r=responses.shift(); if(r instanceof Error) throw r; return r;}} as any);
test("events uses the exact real arena GET contract and preserves public projection",async()=>{let payload:any;const c:any={post:async(_:string,p:any)=>{payload=p;return{events:[card({player_id:"secret",correct_answers:["x"]})]}}};const x=new EventsController(c);await x.load();assert.deepEqual(payload,{mode:"events",action:"get"});assert.equal(renderEventsPage(x).includes("secret"),false);assert.equal(renderEventsPage(x).includes("correct_answers"),false);});
test("guess sends code day answer revision and adopts only server state",async()=>{const c=new EventsController(client([{events:[card()]},{events:[card({progress:{attempts:1,finished:false,solved:false,points:0}})],feedback:{status:"wrong",points:0}}]));await c.load();c.select("cup");await c.submit("  X ");assert.equal(c.getState().events[0].progress.attempts,1);assert.equal(c.getState().feedback?.status,"wrong");});
test("selection, back, unavailable and terminal events are safe",async()=>{const x=new EventsController(client([{events:[card({code:"a"}),card({code:"b",available:false})]}]));await x.load();x.select("b");assert.match(renderEventsPage(x),/not available|non è disponibile|no está disponible/);x.back();assert.equal(x.getState().selectedCode,null);});
test("only HTTPS images render and untrusted content is escaped",async()=>{const x=new EventsController(client([{events:[card({image_url:"javascript:alert(1)",name:"<img>",leaderboard:[{name:"<script>",points:1}]})]}]));await x.load();x.select("cup");const html=renderEventsPage(x);assert.equal(html.includes("javascript:"),false);assert.match(html,/&lt;script&gt;/);});
test("a stale Event A guess cannot overwrite Event B selection",async()=>{let resolve:any;const c:any={post:(_u:string,p:any)=>p.action==="get"?Promise.resolve({events:[card({code:"a"}),card({code:"b"})]}):new Promise(r=>resolve=r)};const x=new EventsController(c);await x.load();x.select("a");const pending=x.submit("answer");x.select("b");resolve({events:[card({code:"a",progress:{attempts:1,finished:false,solved:false,points:0}}),card({code:"b"})],feedback:{status:"wrong",points:0}});await pending;assert.equal(x.getState().selectedCode,"b");assert.equal(x.getState().feedback,null);});
