// Generated by python -m scripts.shop_previews. Do not edit.
export const CARD_PREVIEWS = [
  { style: {"finish": "plain", "ink": "#ecf2f8", "paper": "#0a131e", "glow": "#38bd82"}, url: new URL('../assets/card-previews/figurina_classica.png', import.meta.url).href },
  { style: {"finish": "night", "ink": "#eaf2ff", "paper": "#050c1c", "glow": "#7fc4ff"}, url: new URL('../assets/card-previews/figurina_notturna.png', import.meta.url).href },
  { style: {"finish": "foil", "ink": "#fdf7ff", "paper": "#10112e", "glow": "#ff9ce3"}, url: new URL('../assets/card-previews/figurina_foil.png', import.meta.url).href },
  { style: {"finish": "grain", "ink": "#ede9e2", "paper": "#171614", "glow": "#ded5c4"}, url: new URL('../assets/card-previews/figurina_cinegiornale.png', import.meta.url).href },
  { style: {"finish": "tactics", "paper": "#102925", "ink": "#edfff6", "glow": "#9fffd0"}, url: new URL('../assets/card-previews/referral_lavagna.png', import.meta.url).href },
  { style: {"finish": "eleven", "paper": "#102925", "ink": "#f2ffe4", "glow": "#c8f48b"}, url: new URL('../assets/card-previews/referral_undici_card.png', import.meta.url).href },
  { style: {"finish": "ticket", "paper": "#14222f", "ink": "#f6efdf", "glow": "#edbe7e"}, url: new URL('../assets/card-previews/card_trasferta.png', import.meta.url).href },
  { style: {"finish": "aurora", "paper": "#06121a", "ink": "#eafff8", "glow": "#5ef0b0"}, url: new URL('../assets/card-previews/figurina_aurora.png', import.meta.url).href },
  { style: {"finish": "halftone", "paper": "#1c0a0a", "ink": "#fff1ec", "glow": "#ff5a4d"}, url: new URL('../assets/card-previews/figurina_fanzine.png', import.meta.url).href },
  { style: {"finish": "pixel", "paper": "#05070d", "ink": "#eef3ff", "glow": "#7cff4f"}, url: new URL('../assets/card-previews/figurina_8bit.png', import.meta.url).href },
];
