import { getLanguage, type SupportedLanguage } from "@/i18n";

/**
 * Words of the monthly recap (#245), in the three languages of the game. They live next to
 * the feature, like `i18n/visual.ts`: the story is one self-contained surface.
 */
const MONTHS: Record<SupportedLanguage, string[]> = {
  it: ["gennaio", "febbraio", "marzo", "aprile", "maggio", "giugno", "luglio", "agosto", "settembre", "ottobre", "novembre", "dicembre"],
  es: ["enero", "febrero", "marzo", "abril", "mayo", "junio", "julio", "agosto", "septiembre", "octubre", "noviembre", "diciembre"],
  en: ["January", "February", "March", "April", "May", "June", "July", "August", "September", "October", "November", "December"],
};

type Strings = Record<string, string>;

const STRINGS: Record<SupportedLanguage, Strings> = {
  it: {
    bannerTitle: "Il tuo {month} è pronto",
    bannerSub: "{played} giornate · {solved} indovinati · guardalo",
    profileEntry: "I tuoi recap",
    profileEntrySub: "Il tuo mese in una storia da condividere",
    tooFew: "Per il recap di {month} servono almeno {min} giornate giocate: ne hai giocate {played}.",
    close: "Chiudi",
    pause: "In pausa",
    introKicker: "{name}, ecco il tuo",
    introSub: "Un mese di percorsi misteriosi, in un minuto",
    playedKicker: "Hai giocato",
    playedOf: "/ {days}",
    playedSub: "giornate di {month}.",
    won: "preso", lost: "perso", skip: "saltato",
    solvedKicker: "Calciatori indovinati",
    solvedSub: "e ci hai messo così:",
    attempt: "{n}° tentativo",
    streakTitle: "giorni di fila",
    streakSub: "La tua striscia più lunga del mese.",
    gemKicker: "La tua perla",
    gemTitle: "L'ha indovinato solo il {rate}%",
    gemSub: "Tu ce l'hai fatta, al {attempts}° tentativo.",
    clubKicker: "La tua squadra portafortuna",
    clubSub: "nella carriera di {count} dei tuoi {solved} indovinati",
    styleKicker: "Il tuo stile di gioco",
    "style.professor": "Il Professore", "styleSub.professor": "{value} volte il primo a rispondere. Arrivi prima di tutti.",
    "style.sniper": "Il Cecchino", "styleSub.sniper": "{value} volte al primo colpo. Poche parole, tanti gol.",
    "style.purist": "Il Purista", "styleSub.purist": "Nemmeno un indizio in tutto il mese.",
    "style.last_minute": "L'Ultimo Minuto", "styleSub.last_minute": "{value} volte all'ultimo tentativo. Il brivido ti piace.",
    "style.marathon": "Il Maratoneta", "styleSub.marathon": "{value} giornate su {days}: non ne salti una.",
    "style.playmaker": "Il Regista", "styleSub.playmaker": "Costante, preciso, sempre in partita.",
    communityKicker: "Nel mese sei andato",
    betterThan: "meglio del",
    betterThanSub: "dei giocatori",
    firsts: "{n} volte il più veloce",
    firstsSub: "Bonus del primo che risponde",
    finalSolved: "indovinati", finalStreak: "striscia", finalGem: "la perla", finalRank: "del mese", finalFirstTry: "al primo colpo",
    share: "Condividi nel gruppo",
    again: "Rivedi",
    shareText: "Il mio {month} su Guess the Player: {solved} calciatori indovinati su {played}. Tu quanti ne prendi?",
  },
  es: {
    bannerTitle: "Tu {month} está listo",
    bannerSub: "{played} jornadas · {solved} acertados · míralo",
    profileEntry: "Tus resúmenes",
    profileEntrySub: "Tu mes en una historia para compartir",
    tooFew: "Para el resumen de {month} hacen falta al menos {min} jornadas jugadas: jugaste {played}.",
    close: "Cerrar",
    pause: "En pausa",
    introKicker: "{name}, este es tu",
    introSub: "Un mes de recorridos misteriosos, en un minuto",
    playedKicker: "Jugaste",
    playedOf: "/ {days}",
    playedSub: "jornadas de {month}.",
    won: "acertado", lost: "fallado", skip: "sin jugar",
    solvedKicker: "Futbolistas acertados",
    solvedSub: "y así lo lograste:",
    attempt: "{n}.º intento",
    streakTitle: "días seguidos",
    streakSub: "Tu racha más larga del mes.",
    gemKicker: "Tu joya",
    gemTitle: "Solo lo acertó el {rate}%",
    gemSub: "Tú lo lograste, en el {attempts}.º intento.",
    clubKicker: "Tu equipo de la suerte",
    clubSub: "en la carrera de {count} de tus {solved} acertados",
    styleKicker: "Tu estilo de juego",
    "style.professor": "El Profesor", "styleSub.professor": "{value} veces el primero en responder. Llegas antes que nadie.",
    "style.sniper": "El Francotirador", "styleSub.sniper": "{value} veces a la primera. Pocas palabras, muchos goles.",
    "style.purist": "El Purista", "styleSub.purist": "Ni una pista en todo el mes.",
    "style.last_minute": "El Último Minuto", "styleSub.last_minute": "{value} veces en el último intento. Te gusta sufrir.",
    "style.marathon": "El Maratonista", "styleSub.marathon": "{value} jornadas de {days}: no te pierdes ninguna.",
    "style.playmaker": "El Organizador", "styleSub.playmaker": "Constante, preciso, siempre en el partido.",
    communityKicker: "Este mes quedaste",
    betterThan: "mejor que el",
    betterThanSub: "de los jugadores",
    firsts: "{n} veces el más rápido",
    firstsSub: "Bono del primero en responder",
    finalSolved: "acertados", finalStreak: "racha", finalGem: "la joya", finalRank: "del mes", finalFirstTry: "a la primera",
    share: "Compartir en el grupo",
    again: "Ver otra vez",
    shareText: "Mi {month} en Guess the Player: {solved} futbolistas acertados de {played}. ¿Cuántos sacas tú?",
  },
  en: {
    bannerTitle: "Your {month} is ready",
    bannerSub: "{played} days · {solved} guessed · watch it",
    profileEntry: "Your recaps",
    profileEntrySub: "Your month as a story to share",
    tooFew: "The {month} recap needs at least {min} days played: you played {played}.",
    close: "Close",
    pause: "Paused",
    introKicker: "{name}, here's your",
    introSub: "A month of mystery careers, in one minute",
    playedKicker: "You played",
    playedOf: "/ {days}",
    playedSub: "days in {month}.",
    won: "guessed", lost: "missed", skip: "skipped",
    solvedKicker: "Players guessed",
    solvedSub: "and here's how:",
    attempt: "attempt {n}",
    streakTitle: "days in a row",
    streakSub: "Your longest streak of the month.",
    gemKicker: "Your gem",
    gemTitle: "Only {rate}% guessed it",
    gemSub: "You did, on attempt {attempts}.",
    clubKicker: "Your lucky club",
    clubSub: "in the career of {count} of your {solved} guesses",
    styleKicker: "Your play style",
    "style.professor": "The Professor", "styleSub.professor": "First to answer {value} times. Nobody beats you to it.",
    "style.sniper": "The Sniper", "styleSub.sniper": "{value} first-try guesses. Few words, many goals.",
    "style.purist": "The Purist", "styleSub.purist": "Not a single hint all month.",
    "style.last_minute": "The Last-Minute Hero", "styleSub.last_minute": "{value} guesses on the last attempt. You love the drama.",
    "style.marathon": "The Marathoner", "styleSub.marathon": "{value} days out of {days}: you never miss one.",
    "style.playmaker": "The Playmaker", "styleSub.playmaker": "Steady, precise, always in the game.",
    communityKicker: "This month you did",
    betterThan: "better than",
    betterThanSub: "of players",
    firsts: "fastest {n} times",
    firstsSub: "First-to-answer bonus",
    finalSolved: "guessed", finalStreak: "streak", finalGem: "the gem", finalRank: "of the month", finalFirstTry: "first try",
    share: "Share in a group",
    again: "Watch again",
    shareText: "My {month} on Guess the Player: {solved} players guessed out of {played}. How many can you get?",
  },
};

export function rs(key: string, params: Record<string, string | number> = {}): string {
  const lang = getLanguage();
  const template = STRINGS[lang]?.[key] ?? STRINGS.it[key] ?? key;
  return template.replace(/\{(\w+)\}/g, (_, name) => (name in params ? String(params[name]) : `{${name}}`));
}

export function monthName(month: string): string {
  const index = Number(month.slice(5, 7)) - 1;
  return MONTHS[getLanguage()]?.[index] ?? month;
}
