"""Generate catalogue card samples with the production renderer; no user data or network."""
import hashlib
import json
from pathlib import Path

from PIL import Image

from services.path_image import render_share_card

ROOT = Path(__file__).resolve().parents[1]
TARGET = ROOT / "webapp/src/assets/card-previews"


def generate():
    catalogue = json.loads((ROOT / "data/shop.json").read_text(encoding="utf-8"))
    TARGET.mkdir(parents=True, exist_ok=True)
    entries = []
    for item in catalogue["items"]:
        if item["kind"] != "card":
            continue
        style = item["style"]
        result = render_share_card(412, 2, 3, name="PLAYER", shirt="10", style=style)
        with Image.open(result) as image:
            image.thumbnail((400, 500))
            image.save(TARGET / f"{item['id']}.png", optimize=True)
        entries.append({"id": item["id"], "style": style})
    renderer_hash = hashlib.sha256((ROOT / "services/path_image.py").read_text(encoding="utf-8").encode("utf-8")).hexdigest()
    (TARGET / "manifest.json").write_text(
        json.dumps({"renderer_sha256": renderer_hash, "cards": entries}, ensure_ascii=False, indent=2) + "\n",
        encoding="utf-8",
    )
    lines = ["// Generated by python -m scripts.shop_previews. Do not edit.", "export const CARD_PREVIEWS = ["]
    for entry in entries:
        lines.append("  { style: " + json.dumps(entry["style"]) + ", url: new URL('../assets/card-previews/"
                     + entry["id"] + ".png', import.meta.url).href },")
    lines.append("];")
    (ROOT / "webapp/src/appearance/card-previews.ts").write_text("\n".join(lines) + "\n", encoding="utf-8")


if __name__ == "__main__":
    generate()
