/*
  Le stringhe della mini app, nelle tre lingue del gioco.

  Stanno fuori da index.html per la stessa ragione per cui ci stanno le funzioni pure di
  client.js: cosi' `node --test` puo' caricarle senza un browser. Il test che conta e' quello
  di parita' (tests/client.test.cjs): le tre lingue devono avere **esattamente** le stesse
  chiavi, oggetti annidati compresi. E' il gemello di tests/test_i18n_keys.py, che fa lo
  stesso controllo sui messaggi del bot: senza, una chiave aggiunta solo in italiano non si
  nota, perche' l'interfaccia non va in errore - scrive "undefined" e va avanti.

  Le tre tabelle restano separate perche' rispondono a schermate diverse: `T` e' la mini app,
  `PUBLIC_TEXT` il profilo pubblico di un altro giocatore, `SHOP_I18N` il negozio.
*/
(function (root) {
"use strict";

const T = {
  it: {
    play: "Gioca", archive: "Archivio", stats: "Statistiche", leagues: "Leghe",
    todayTitle: "Sfida di oggi", solved: "Indovinata", notPlayed: "Non ancora giocata",
    left: "Tentativi rimasti", none: "Nessuna sfida disponibile", points: "punti",
    difficulty: "Difficoltà", bonus: "💎 +1 punto al primo che risponde",
    placeholder: "Scrivi il nome del calciatore", guessBtn: "Indovina",
    hintBtn: "💡 Indizio (-1 punto)", hintsLeft: "indizi rimasti", noHints: "Niente indizi per questa sfida",
    correct: "Indovinato!", wrong: "Sbagliato.", gotPoints: "punti guadagnati",
    outOfAttempts: "Tentativi finiti. Il nome arriva a mezzanotte.",
    compared: "Rispetto a", sameNat: "🌍 Stessa nazionalità", diffNat: "🌍 Nazionalità diversa",
    samePos: "🧭 Stesso ruolo", diffPos: "🧭 Ruolo diverso",
    older: "⬆️ Più vecchio del", younger: "⬇️ Più giovane del", sameYear: "🎂 Stesso anno:",
    share: "Condividi il risultato", answerWas: "Era",
    yourNumbers: "I tuoi numeri", total: "Punti totali", monthly: "Punti del mese",
    streak: "Striscia", best: "Record", guessed: "Indovinati", recovered: "Recuperate",
    trophies: "Trofei", distribution: "In quanti tentativi la prendi", noGames: "Nessuna partita ancora.",
    cabinet: "La tua bacheca", cabinetHint: "Scegline fino a {n} da tenere sul profilo.",
    cabinetOpen: "Apri la bacheca", cabinetTitle: "Bacheca", cabinetBack: "Indietro",
    showCard: "Vedi la figurina", cardHint: "Tieni premuto sull'immagine per salvarla o inoltrarla.",
    cabinetGold: "Primi posti", cabinetSilver: "Secondi", cabinetBronze: "Terzi",
    cabinetAll: "Tutti", cabinetEvents: "Eventi", cabinetMonthly: "Mensili",
    cabinetNone: "Nessun trofeo con questo filtro.",
    cabinetPin: "Appendi", cabinetPinned: "Sul profilo",
    showcaseTitle: "Vetrina della settimana", showcaseWeek: "Settimana {n}",
    rarity: { free: "Compreso", earned: "Guadagnato", common: "Comune", rare: "Raro", collector: "Da collezione" },
    completeWith: "Si ottiene completando", completeMissing: "Manca ancora",
    welcomeOnly: "Solo come primo acquisto", podiumOnly: "Si vince sul podio",
    noTrophies: "Nessun trofeo ancora. Si vincono sul podio di un evento o della classifica del mese.",
    pinned: "Sul profilo", pinSaved: "Bacheca aggiornata", pinFull: "Puoi tenerne al massimo {n}.",
    leaderboard: "Classifica", myLeagues: "Le tue leghe", noLeagues: "Non fai parte di nessuna lega.",
    createLeague: "Crea una lega", leagueName: "Nome della lega", create: "Crea",
    joinLeague: "Entra con un codice", leagueCode: "Codice", join: "Entra",
    leave: "Esci", leaveConfirm: "Uscire dalla lega? I punti fatti lì dentro si perdono.",
    invite: "Invita", members: "membri",
    calendarTitle: "Ultime giornate", playDay: "Gioca questa giornata",
    legendSolved: "presa", legendLost: "persa", legendRecovered: "recuperata", legendMissed: "non giocata",
    noArchive: "Non ci sono ancora giornate passate.", back: "Indietro",
    archiveNote: "Le giornate passate non danno punti.",
    error: "Apri questa pagina dal bot per vedere i tuoi dati.",
    notRegistered: "Fai /start nel bot per iniziare a giocare.",
    loading: "Carico…", already: "Hai già giocato questa giornata.",
    shop: "Negozio",
    shopHeadline: "Il tuo gioco. Il tuo stile.",
    shopSubtitle: "Dai carattere al profilo, colora le tue sfide e fatti riconoscere in classifica.",
    shopCosmetics: "Solo estetica",
    shopPreview: "Anteprima",
    shopBuy: "Acquista",
    shopCollections: "Modi di vivere il calcio",
    shopCollectionNav: "Collezioni",
    shopSet: "Look coordinato · 5 oggetti",
    privacy: "Privacy",
    refunds: "Termini e rimborsi",
    shopFair: "Solo roba da guardare: niente punti, niente tentativi in più, niente indizi gratis.",
    shopSections: {
      theme: "Temi", frame: "Cornici", title: "Titoli",
      badge: "Distintivi", squares: "Quadratini", number: "Numeri",
      celebration: "Festeggiamenti", card: "Figurine", bundle: "Pacchetti",
    },
    shopWear: "Indossa", shopWorn: "👕 Addosso", shopOwned: "✅ Già tuo",
    shopThanks: "Grazie! È tuo.", shopWaiting: "Consegna in corso…",
    shopErrors: {
      already_owned: "Ce l'hai già.", not_for_sale: "Non si compra da solo.",
      unknown_item: "Questo oggetto non esiste più.", not_owned: "Devi prima comprarlo.",
      not_equippable: "Questa collezione contiene più alternative: scegli i singoli oggetti da indossare.",
    },
    leagueErrors: {
      limit: "Sei già in 5 leghe.", name_too_long: "Nome troppo lungo (max 30).",
      no_name: "Serve un nome.", no_code: "Serve un codice.",
      not_found: "Codice inesistente.", already_member: "Sei già in questa lega.",
      full: "Lega piena.", failed: "Non è stato possibile creare la lega.",
      not_member: "Non sei in questa lega.",
    },
  },
  es: {
    play: "Jugar", archive: "Archivo", stats: "Estadísticas", leagues: "Ligas",
    todayTitle: "Desafío de hoy", solved: "Acertado", notPlayed: "Sin jugar todavía",
    left: "Intentos restantes", none: "No hay desafío disponible", points: "puntos",
    difficulty: "Dificultad", bonus: "💎 +1 punto para el primero",
    placeholder: "Escribe el nombre del futbolista", guessBtn: "Adivinar",
    hintBtn: "💡 Pista (-1 punto)", hintsLeft: "pistas restantes", noHints: "Sin pistas para este desafío",
    correct: "¡Acertado!", wrong: "Incorrecto.", gotPoints: "puntos ganados",
    outOfAttempts: "Se acabaron los intentos. El nombre llega a medianoche.",
    compared: "Respecto a", sameNat: "🌍 Misma nacionalidad", diffNat: "🌍 Nacionalidad distinta",
    samePos: "🧭 Misma posición", diffPos: "🧭 Posición distinta",
    older: "⬆️ Más viejo que", younger: "⬇️ Más joven que", sameYear: "🎂 Mismo año:",
    share: "Compartir el resultado", answerWas: "Era",
    yourNumbers: "Tus números", total: "Puntos totales", monthly: "Puntos del mes",
    streak: "Racha", best: "Récord", guessed: "Acertados", recovered: "Recuperados",
    trophies: "Trofeos", distribution: "En cuántos intentos aciertas", noGames: "Todavía sin partidas.",
    cabinet: "Tu vitrina", cabinetHint: "Elige hasta {n} para llevar en el perfil.",
    cabinetOpen: "Abrir la vitrina", cabinetTitle: "Vitrina", cabinetBack: "Atrás",
    showCard: "Ver el cromo", cardHint: "Mantén pulsada la imagen para guardarla o reenviarla.",
    cabinetGold: "Primeros puestos", cabinetSilver: "Segundos", cabinetBronze: "Terceros",
    cabinetAll: "Todos", cabinetEvents: "Eventos", cabinetMonthly: "Mensuales",
    cabinetNone: "Ningún trofeo con este filtro.",
    cabinetPin: "Colgar", cabinetPinned: "En el perfil",
    showcaseTitle: "Escaparate de la semana", showcaseWeek: "Semana {n}",
    rarity: { free: "Incluido", earned: "Ganado", common: "Común", rare: "Raro", collector: "De colección" },
    completeWith: "Se consigue completando", completeMissing: "Todavía falta",
    welcomeOnly: "Solo como primera compra", podiumOnly: "Se gana en el podio",
    noTrophies: "Todavía ningún trofeo. Se ganan en el podio de un evento o de la clasificación del mes.",
    pinned: "En el perfil", pinSaved: "Vitrina actualizada", pinFull: "Puedes llevar como máximo {n}.",
    leaderboard: "Clasificación", myLeagues: "Tus ligas", noLeagues: "No estás en ninguna liga.",
    createLeague: "Crear una liga", leagueName: "Nombre de la liga", create: "Crear",
    joinLeague: "Entrar con un código", leagueCode: "Código", join: "Entrar",
    leave: "Salir", leaveConfirm: "¿Salir de la liga? Se pierden los puntos hechos ahí.",
    invite: "Invitar", members: "miembros",
    calendarTitle: "Últimos días", playDay: "Jugar este día",
    legendSolved: "acertado", legendLost: "fallado", legendRecovered: "recuperado", legendMissed: "sin jugar",
    noArchive: "Todavía no hay días pasados.", back: "Atrás",
    archiveNote: "Los días pasados no dan puntos.",
    error: "Abre esta página desde el bot para ver tus datos.",
    notRegistered: "Envía /start en el bot para empezar a jugar.",
    loading: "Cargando…", already: "Ya has jugado este día.",
    shop: "Tienda",
    shopHeadline: "Tu juego. Tu estilo.",
    shopSubtitle: "Dale personalidad a tu perfil, colorea tus retos y destaca en la clasificación.",
    shopCosmetics: "Solo estética",
    shopPreview: "Vista previa",
    shopBuy: "Comprar",
    shopCollections: "Formas de vivir el fútbol",
    shopCollectionNav: "Colecciones",
    shopSet: "Look a juego · 5 objetos",
    privacy: "Privacidad",
    refunds: "Términos y reembolsos",
    shopFair: "Solo cosas para mirar: ni puntos, ni intentos de más, ni pistas gratis.",
    shopSections: {
      theme: "Temas", frame: "Marcos", title: "Títulos",
      badge: "Distintivos", squares: "Cuadrados", number: "Números",
      celebration: "Celebraciones", card: "Cromos", bundle: "Packs",
    },
    shopWear: "Ponérselo", shopWorn: "👕 Puesto", shopOwned: "✅ Ya es tuyo",
    shopThanks: "¡Gracias! Ya es tuyo.", shopWaiting: "Entregando…",
    shopErrors: {
      already_owned: "Ya lo tienes.", not_for_sale: "No se compra suelto.",
      unknown_item: "Este objeto ya no existe.", not_owned: "Primero tienes que comprarlo.",
      not_equippable: "Esta colección contiene varias alternativas: elige los objetos que quieres ponerte.",
    },
    leagueErrors: {
      limit: "Ya estás en 5 ligas.", name_too_long: "Nombre demasiado largo (máx 30).",
      no_name: "Hace falta un nombre.", no_code: "Hace falta un código.",
      not_found: "Código inexistente.", already_member: "Ya estás en esta liga.",
      full: "Liga llena.", failed: "No se ha podido crear la liga.",
      not_member: "No estás en esta liga.",
    },
  },
  en: {
    play: "Play", archive: "Archive", stats: "Stats", leagues: "Leagues",
    todayTitle: "Today's challenge", solved: "Solved", notPlayed: "Not played yet",
    left: "Attempts left", none: "No challenge available", points: "points",
    difficulty: "Difficulty", bonus: "💎 +1 point for the first to answer",
    placeholder: "Type the player's name", guessBtn: "Guess",
    hintBtn: "💡 Hint (-1 point)", hintsLeft: "hints left", noHints: "No hints for this challenge",
    correct: "Got it!", wrong: "Wrong.", gotPoints: "points earned",
    outOfAttempts: "Out of attempts. The name comes at midnight.",
    compared: "Compared with", sameNat: "🌍 Same nationality", diffNat: "🌍 Different nationality",
    samePos: "🧭 Same position", diffPos: "🧭 Different position",
    older: "⬆️ Older than", younger: "⬇️ Younger than", sameYear: "🎂 Same year:",
    share: "Share the result", answerWas: "It was",
    yourNumbers: "Your numbers", total: "Total points", monthly: "Points this month",
    streak: "Streak", best: "Best", guessed: "Guessed", recovered: "Recovered",
    trophies: "Trophies", distribution: "How many attempts it takes you", noGames: "No games yet.",
    cabinet: "Your cabinet", cabinetHint: "Pick up to {n} to keep on your profile.",
    cabinetOpen: "Open the cabinet", cabinetTitle: "Cabinet", cabinetBack: "Back",
    showCard: "See the card", cardHint: "Press and hold the image to save or forward it.",
    cabinetGold: "First places", cabinetSilver: "Seconds", cabinetBronze: "Thirds",
    cabinetAll: "All", cabinetEvents: "Events", cabinetMonthly: "Monthly",
    cabinetNone: "No trophy matches this filter.",
    cabinetPin: "Pin", cabinetPinned: "On the profile",
    showcaseTitle: "This week's window", showcaseWeek: "Week {n}",
    rarity: { free: "Included", earned: "Earned", common: "Common", rare: "Rare", collector: "Collector" },
    completeWith: "Comes from completing", completeMissing: "Still missing",
    welcomeOnly: "First purchase only", podiumOnly: "Won on the podium",
    noTrophies: "No trophies yet. They are won on the podium of an event or of the monthly leaderboard.",
    pinned: "On the profile", pinSaved: "Cabinet updated", pinFull: "You can keep at most {n}.",
    leaderboard: "Leaderboard", myLeagues: "Your leagues", noLeagues: "You're not in any league.",
    createLeague: "Create a league", leagueName: "League name", create: "Create",
    joinLeague: "Join with a code", leagueCode: "Code", join: "Join",
    leave: "Leave", leaveConfirm: "Leave the league? The points made there are lost.",
    invite: "Invite", members: "members",
    calendarTitle: "Recent days", playDay: "Play this day",
    legendSolved: "solved", legendLost: "lost", legendRecovered: "recovered", legendMissed: "not played",
    noArchive: "There are no past days yet.", back: "Back",
    archiveNote: "Past days award no points.",
    error: "Open this page from the bot to see your data.",
    notRegistered: "Send /start in the bot to start playing.",
    loading: "Loading…", already: "You have already played this day.",
    shop: "Shop",
    shopHeadline: "Your game. Your style.",
    shopSubtitle: "Give your profile personality, add colour to your challenges and stand out on the leaderboard.",
    shopCosmetics: "Cosmetics only",
    shopPreview: "Preview",
    shopBuy: "Buy",
    shopCollections: "Ways to live football",
    shopCollectionNav: "Collections",
    shopSet: "Matching look · 5 items",
    privacy: "Privacy",
    refunds: "Terms and refunds",
    shopFair: "Things to look at only: no points, no extra attempts, no free hints.",
    shopSections: {
      theme: "Themes", frame: "Frames", title: "Titles",
      badge: "Badges", squares: "Squares", number: "Numbers",
      celebration: "Celebrations", card: "Cards", bundle: "Packs",
    },
    shopWear: "Wear it", shopWorn: "👕 Worn", shopOwned: "✅ Yours",
    shopThanks: "Thank you! It's yours.", shopWaiting: "Delivering…",
    shopErrors: {
      already_owned: "You already have it.", not_for_sale: "Not sold on its own.",
      unknown_item: "This item no longer exists.", not_owned: "You have to buy it first.",
      not_equippable: "This collection contains multiple alternatives: choose the individual items to wear.",
    },
    leagueErrors: {
      limit: "You are already in 5 leagues.", name_too_long: "Name too long (max 30).",
      no_name: "A name is needed.", no_code: "A code is needed.",
      not_found: "No such code.", already_member: "You are already in this league.",
      full: "League full.", failed: "The league could not be created.",
      not_member: "You are not in this league.",
    },
  },
};

const PUBLIC_TEXT = {
  it: {open:"Apri profilo", title:"Profilo giocatore", wearing:"Il look indossato", numbers:"Statistiche di gioco", back:"Torna alla classifica", unavailable:"Profilo non disponibile. Potrebbe essere stato eliminato.", retry:"Riprova", hint:"Tocca un nome per vedere il profilo e il suo look.", example:"Simboli del risultato · esempio", searchTitle:"Cerca giocatori", searchPlaceholder:"Nome del giocatore", searchButton:"Cerca", searchHint:"Inserisci almeno 2 caratteri.", searchNone:"Nessun giocatore trovato.", searchError:"Ricerca non riuscita. Riprova."},
  es: {open:"Abrir perfil", title:"Perfil del jugador", wearing:"Su look actual", numbers:"Estadísticas de juego", back:"Volver a la clasificación", unavailable:"Perfil no disponible. Puede que se haya eliminado.", retry:"Reintentar", hint:"Toca un nombre para ver su perfil y su look.", example:"Símbolos del resultado · ejemplo", searchTitle:"Buscar jugadores", searchPlaceholder:"Nombre del jugador", searchButton:"Buscar", searchHint:"Escribe al menos 2 caracteres.", searchNone:"No se encontraron jugadores.", searchError:"No se pudo buscar. Inténtalo de nuevo."},
  en: {open:"Open profile", title:"Player profile", wearing:"Current look", numbers:"Game statistics", back:"Back to leaderboard", unavailable:"Profile unavailable. It may have been deleted.", retry:"Retry", hint:"Tap a name to see their profile and look.", example:"Result symbols · example", searchTitle:"Find players", searchPlaceholder:"Player name", searchButton:"Search", searchHint:"Enter at least 2 characters.", searchNone:"No players found.", searchError:"Search failed. Try again."}
};

const SHOP_I18N = {
  "it": {
    "details": "Dettagli", "included": "oggetti inclusi",
    "catalog": "Catalogo",
    "wardrobe": "I miei oggetti",
    "history": "Acquisti",
    "achievements": "Traguardi",
    "all": "Tutte le categorie",
    "anyPrice": "Qualsiasi prezzo",
    "hideOwned": "Nascondi già miei",
    "tryOn": "Prova",
    "preview": "Stai provando",
    "stop": "Termina prova",
    "previewHint": "La prova è temporanea. Non acquista e non salva oggetti.",
    "wearAll": "Indossa tutto",
    "save": "Salva look attuale",
    "name": "Nome del look",
    "saved": "Look salvato",
    "remove": "Elimina",
    "empty": "Nessun oggetto con questi filtri.",
    "looks": "I tuoi look · massimo 5",
    "partial": "Prezzo per i soli pezzi mancanti",
    "missing": "Ti mancano",
    "owned": "Già tuo",
    "earn": "Si conquista giocando",
    "unlocked": "Traguardo sbloccato",
    "refunded": "Rimborsato",
    "paid": "Acquisto completato",
    "noHistory": "Non hai ancora effettuato acquisti.",
    "support": "Assistenza e rimborso",
    "supportHint": "Copia il comando e invialo nella chat del bot. Puoi chiedere un rimborso entro 21 giorni dall’acquisto.",
    "supportRequest": "Richiedo assistenza o rimborso per l’acquisto",
    "copy": "Copia comando",
    "copied": "Comando copiato",
    "openBot": "Apri la chat del bot",
    "retry": "Riprova",
    "loadError": "Non riesco a caricare i dati. Riprova.",
    "invalid_name": "Inserisci un nome da 1 a 30 caratteri.",
    "look_limit": "Hai già 5 look. Eliminane uno o usa lo stesso nome per sostituirlo.",
    "price_changed": "Il prezzo è cambiato. Riapri il negozio.",
    "waiting": "Il pagamento è confermato. La consegna è ancora in corso: aggiorna il negozio tra poco."
  },
  "es": {
    "details": "Detalles", "included": "objetos incluidos",
    "catalog": "Catálogo",
    "wardrobe": "Mis objetos",
    "history": "Compras",
    "achievements": "Logros",
    "all": "Todas las categorías",
    "anyPrice": "Cualquier precio",
    "hideOwned": "Ocultar los que tengo",
    "tryOn": "Probar",
    "preview": "Estás probando",
    "stop": "Terminar prueba",
    "previewHint": "La prueba es temporal. No compra ni guarda objetos.",
    "wearAll": "Ponerse todo",
    "save": "Guardar look actual",
    "name": "Nombre del look",
    "saved": "Look guardado",
    "remove": "Eliminar",
    "empty": "No hay objetos con estos filtros.",
    "looks": "Tus looks · máximo 5",
    "partial": "Precio por las piezas que faltan",
    "missing": "Te faltan",
    "owned": "Ya es tuyo",
    "earn": "Se consigue jugando",
    "unlocked": "Logro desbloqueado",
    "refunded": "Reembolsado",
    "paid": "Compra completada",
    "noHistory": "Todavía no has hecho compras.",
    "support": "Ayuda y reembolso",
    "supportHint": "Copia el comando y envíalo en el chat del bot. Puedes pedir un reembolso dentro de 21 días de la compra.",
    "supportRequest": "Solicito ayuda o reembolso para la compra",
    "copy": "Copiar comando",
    "copied": "Comando copiado",
    "openBot": "Abrir chat del bot",
    "retry": "Reintentar",
    "loadError": "No se pueden cargar los datos. Inténtalo de nuevo.",
    "invalid_name": "Escribe un nombre de 1 a 30 caracteres.",
    "look_limit": "Ya tienes 5 looks. Borra uno o usa el mismo nombre para sustituirlo.",
    "price_changed": "El precio ha cambiado. Abre la tienda de nuevo.",
    "waiting": "Pago confirmado. La entrega sigue en curso: actualiza la tienda en un momento."
  },
  "en": {
    "details": "Details", "included": "items included",
    "catalog": "Catalogue",
    "wardrobe": "My items",
    "history": "Purchases",
    "achievements": "Milestones",
    "all": "All categories",
    "anyPrice": "Any price",
    "hideOwned": "Hide owned items",
    "tryOn": "Try on",
    "preview": "Trying on",
    "stop": "End preview",
    "previewHint": "This preview is temporary. It does not buy or save items.",
    "wearAll": "Wear full set",
    "save": "Save current look",
    "name": "Look name",
    "saved": "Look saved",
    "remove": "Delete",
    "empty": "No items match these filters.",
    "looks": "Your looks · maximum 5",
    "partial": "Price for the missing pieces only",
    "missing": "Missing",
    "owned": "Already yours",
    "earn": "Earn by playing",
    "unlocked": "Milestone unlocked",
    "refunded": "Refunded",
    "paid": "Purchase completed",
    "noHistory": "You have not made any purchases yet.",
    "support": "Support and refunds",
    "supportHint": "Copy the command and send it in the bot chat. You can request a refund within 21 days of purchase.",
    "supportRequest": "I request support or a refund for purchase",
    "copy": "Copy command",
    "copied": "Command copied",
    "openBot": "Open bot chat",
    "retry": "Retry",
    "loadError": "Could not load the data. Please retry.",
    "invalid_name": "Enter a name between 1 and 30 characters.",
    "look_limit": "You already have 5 looks. Delete one or reuse a name to replace it.",
    "price_changed": "The price changed. Reopen the shop.",
    "waiting": "Payment confirmed. Delivery is still in progress: refresh the shop shortly."
  }
};

const strings = { T, PUBLIC_TEXT, SHOP_I18N };
if (typeof module !== "undefined" && module.exports) module.exports = strings;
else root.PlayerStrings = strings;
})(typeof globalThis !== "undefined" ? globalThis : this);
